FROM trawor/alpine
ARG VERSION=0.154.3
RUN apk update && apk add tzdata --no-cache

RUN wget "https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz" -O hugo.tar.gz

RUN tar -zxvf hugo.tar.gz && mv ./hugo /bin/ && rm hugo.tar.gz && mkdir -p /blog


WORKDIR /blog
VOLUME [ "/blog" ]
EXPOSE 1313
ENV TZ=Asia/Shanghai

CMD /bin/hugo server --bind 0.0.0.0 -D
